use_frameworks!

target 'Bamboots_Example' do
  pod 'Bamboots', :path => '../'
  pod 'Bamboots/BambootsProtobuf', :path => '../'
  pod 'SnapKit'
  target 'Bamboots_ExampleTests' do
      inherit! :search_paths
  end
end

#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#            config.build_settings['SWIFT_VERSION'] = '4.0'
#        end
#    end
#end

