use_frameworks!

target 'MBNetwork_Example' do
  pod 'MBNetwork', :path => '../'
  pod 'SnapKit'
  target 'MBNetwork_Tests' do
      inherit! :search_paths
      
      
  end
end

post_install do |installer|
    installer.pods_project.build_configurations.build_settings['SWIFT_VERSION'] = '3.0'
end
